[theme]
base = "dark"
primaryColor = "#00BEF0"
backgroundColor = "#0D1B2A"
secondaryBackgroundColor = "#152840"
textColor = "#D0E8FF"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
